### PR TITLE
Minimal failing example for forward declared unique_ptr

### PR DESCRIPTION
**Pull request by daravi**
Tried with G++ 7.3.1 20180303 (Red Hat 7.3.1-5)

I am not familiar with meson so you would have to modify it now that I have added main.cpp

### CODE REVIEW

**Comment by szaszm** [comment]
Neither am I familiar with meson, this was a first try, but sure, no problem.
I'll continue with this in the evening (UTC+2)

**Comment by szaszm** [comment]
I could reproduce the issue with these changes even on my gcc 8.3.0 installation, on linux.
Strangely, it doesn't occur with clang even though they're both using libstdc++. I had a look into the related system headers but there's nothing in `unique_ptr` that would trigger the instantiation of `std::default_delete<...>::operator()` outside `~Foo()` implementation.
`std::default_delete<...>` itself gets instantiated, but that doesn't mean instantiation of member definitions.

**Comment by daravi** [comment]
Yes it seems to be a bug in GCC:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85552
Related bug in Clang:
https://bugs.llvm.org/show_bug.cgi?id=39363
[Richard Smith]
> The list-initialization case does not potentially-invoke the destructor in C++11 or C++14 either (unlike non-list copy-initialization, list-initialization directly executes a constructor on the destination object even in C++11, and as a result there is no temporary object created to trigger the potential invocation of a destructor). Clang gets that case right, but GCC has another bug there... So: two bugs in GCC (though they might be the same thing), one bug in Clang's C++17 support, one bug in libstdc++, and no bugs in libc++
https://bugs.llvm.org/show_bug.cgi?id=39363#c8

**Comment by szaszm** [comment]
Since the issue is known and already reported, I'll archive this repo now. Thanks for the contribution! :)

**Pull request merged**
